package com.etheller.warsmash.viewer5.handlers.w3x.simulation.unit;

public enum StateModBuffType {
	ETHEREAL,
	RESISTANT,
	SLEEPING,
	STUN,
	MAGIC_IMMUNE,
	SNARED,
	DISABLE_AUTO_ATTACK,
	DISABLE_ATTACK,
	DISABLE_MELEE_ATTACK,
	DISABLE_RANGED_ATTACK,
	DISABLE_SPECIAL_ATTACK,
	DISABLE_SPELLS,
	INVULNERABLE;
}