package com.etheller.warsmash.viewer5.handlers.w3x.simulation.abilitybuilder.parser;

public enum AbilityBuilderType {
	NORMAL_AUTOTARGET,
	NORMAL_FLEXTARGET_SIMPLE,
	NORMAL_UNITTARGET_SIMPLE,
	NORMAL_POINTTARGET_SIMPLE,
	NORMAL_NOTARGET_SIMPLE,
	NORMAL_FLEXTARGET,
	NORMAL_UNITTARGET,
	NORMAL_POINTTARGET,
	NORMAL_NOTARGET,
	TOGGLE,
	TOGGLE_TICKING,
	SMART,
	BUFF,
	TICKING_PASSIVE,
	PASSIVE,
	TEMPLATE,
	HIDDEN;
}
