package com.etheller.warsmash.viewer5.handlers.w3x;

import java.util.ArrayList;
import java.util.List;

public class Variations {
	public static final List<String> CLIFF_VARS;
	public static final List<String> CITY_CLIFF_VARS;
	public static final int MAX_VAR = 4;

	static {
		final List<String> cliffVariations = new ArrayList<>();
		cliffVariations.add("AAAB");
		cliffVariations.add("AAAC");
		cliffVariations.add("AABA");
		cliffVariations.add("AABB");
		cliffVariations.add("AABC");
		cliffVariations.add("AACA");
		cliffVariations.add("AACB");
		cliffVariations.add("AACC");
		cliffVariations.add("ABAA");
		cliffVariations.add("ABAB");
		cliffVariations.add("ABAC");
		cliffVariations.add("ABBA");
		cliffVariations.add("ABBB");
		cliffVariations.add("ABBC");
		cliffVariations.add("ABCA");
		cliffVariations.add("ABCB");
		cliffVariations.add("ABCC");
		cliffVariations.add("ACAA");
		cliffVariations.add("ACAB");
		cliffVariations.add("ACAC");
		cliffVariations.add("ACBA");
		cliffVariations.add("ACBB");
		cliffVariations.add("ACBC");
		cliffVariations.add("ACCA");
		cliffVariations.add("ACCB");
		cliffVariations.add("ACCC");
		cliffVariations.add("BAAA");
		cliffVariations.add("BAAB");
		cliffVariations.add("BAAC");
		cliffVariations.add("BABA");
		cliffVariations.add("BABB");
		cliffVariations.add("BABC");
		cliffVariations.add("BACA");
		cliffVariations.add("BACB");
		cliffVariations.add("BACC");
		cliffVariations.add("BBAA");
		cliffVariations.add("BBAB");
		cliffVariations.add("BBAC");
		cliffVariations.add("BBBA");
		cliffVariations.add("BBCA");
		cliffVariations.add("BCAA");
		cliffVariations.add("BCAB");
		cliffVariations.add("BCAC");
		cliffVariations.add("BCBA");
		cliffVariations.add("BCCA");
		cliffVariations.add("CAAA");
		cliffVariations.add("CAAB");
		cliffVariations.add("CAAC");
		cliffVariations.add("CABA");
		cliffVariations.add("CABB");
		cliffVariations.add("CABC");
		cliffVariations.add("CACA");
		cliffVariations.add("CACB");
		cliffVariations.add("CACC");
		cliffVariations.add("CBAA");
		cliffVariations.add("CBAB");
		cliffVariations.add("CBAC");
		cliffVariations.add("CBBA");
		cliffVariations.add("CBCA");
		cliffVariations.add("CCAA");
		cliffVariations.add("CCAB");
		cliffVariations.add("CCAC");
		cliffVariations.add("CCBA");
		cliffVariations.add("CCCA");
		CLIFF_VARS = cliffVariations;

		final List<String> cityCliffVariations = new ArrayList<>();
		cityCliffVariations.add("AAAB");
		cityCliffVariations.add("AAAC");
		cityCliffVariations.add("AABA");
		cityCliffVariations.add("AABB");
		cityCliffVariations.add("AABC");
		cityCliffVariations.add("AACA");
		cityCliffVariations.add("AACB");
		cityCliffVariations.add("AACC");
		cityCliffVariations.add("ABAA");
		cityCliffVariations.add("ABAB");
		cityCliffVariations.add("ABAC");
		cityCliffVariations.add("ABBA");
		cityCliffVariations.add("ABBB");
		cityCliffVariations.add("ABBC");
		cityCliffVariations.add("ABCA");
		cityCliffVariations.add("ABCB");
		cityCliffVariations.add("ABCC");
		cityCliffVariations.add("ACAA");
		cityCliffVariations.add("ACAB");
		cityCliffVariations.add("ACAC");
		cityCliffVariations.add("ACBA");
		cityCliffVariations.add("ACBB");
		cityCliffVariations.add("ACBC");
		cityCliffVariations.add("ACCA");
		cityCliffVariations.add("ACCB");
		cityCliffVariations.add("ACCC");
		cityCliffVariations.add("BAAA");
		cityCliffVariations.add("BAAB");
		cityCliffVariations.add("BAAC");
		cityCliffVariations.add("BABA");
		cityCliffVariations.add("BABB");
		cityCliffVariations.add("BABC");
		cityCliffVariations.add("BACA");
		cityCliffVariations.add("BACB");
		cityCliffVariations.add("BACC");
		cityCliffVariations.add("BBAA");
		cityCliffVariations.add("BBAB");
		cityCliffVariations.add("BBAC");
		cityCliffVariations.add("BBBA");
		cityCliffVariations.add("BBCA");
		cityCliffVariations.add("BCAA");
		cityCliffVariations.add("BCAB");
		cityCliffVariations.add("BCAC");
		cityCliffVariations.add("BCBA");
		cityCliffVariations.add("BCCA");
		cityCliffVariations.add("CAAA");
		cityCliffVariations.add("CAAB");
		cityCliffVariations.add("CAAC");
		cityCliffVariations.add("CABA");
		cityCliffVariations.add("CABB");
		cityCliffVariations.add("CABC");
		cityCliffVariations.add("CACA");
		cityCliffVariations.add("CACB");
		cityCliffVariations.add("CACC");
		cityCliffVariations.add("CBAA");
		cityCliffVariations.add("CBAB");
		cityCliffVariations.add("CBAC");
		cityCliffVariations.add("CBBA");
		cityCliffVariations.add("CBCA");
		cityCliffVariations.add("CCAA");
		cityCliffVariations.add("CCAB");
		cityCliffVariations.add("CCAC");
		cityCliffVariations.add("CCBA");
		cityCliffVariations.add("CCCA");
		CITY_CLIFF_VARS = cityCliffVariations;
	}

	public static int getCliffVariation(final String dir, final String tag, final int variation) {
		return variation;
	}
}
